### ISSUE TITLE
第六回中，「玉璽琢自祖龍...亦其見之不明耳」是前言，不是正文

### ISSUE THREAD

**Issue by scju** [Ancient-China-Books/sanguoyanyi#1]
[玉璽琢自祖龍，則祖龍以前，夏、商、周之爲天子，何嘗有玉璽耶？況祖龍三十六年玉璽失而復得，而祖龍即於明年死，是失之不足憂，得之不足喜也。孫堅舉動，頗有忠義之氣，一得玉璽，而忽懷異心，亦其見之不明耳。](https://ancient-china-books.github.io/sanguoyanyi/OEBPS/Text/382.html#p6)
--
這一段應屬前言，不是正文，應該用藍色小字。

**Comment by douglarek** [comment]
多谢指正，会修。
